print("Day 1 - Python Print Function")
print("The function is declared like this:")
print("print('what to print')")
print("--------------------------------------------")
print("Day 1 - String Manipulation")
print("String Concatenation is done with the " + " sign.")
print('e.g. print("Hello " + "world")')
print("New lines can be created with a backslash and n.")
print("--------------------------------------------")
input("What is your name?\n")
print("Hello " + input("What is your name?\n"))
print("--------------------------------------------")
print(len(input("what is your name?\n")))
print("--------------------------------------------")
a = input("a: ")
b = input("b: ")
c = a
a = b
b = c
print("a = " + a)
print("b = " + b)
print("--------------------------------------------")
print("Welcome to band name generator 2.0")
city_name = input("What is your City name?\n")
pet_name = input("\nwhat is the name of your pet?\n")
print("Name of your band can be: " + city_name + " " + pet_name)
